config {
  type: "table"
}

WITH call_sources AS (
  SELECT DISTINCT source
  FROM callrail.Calls
)

SELECT
  source,
  CASE
    WHEN 
      REGEXP_CONTAINS(LOWER(source), 'google ad') 
      AND NOT REGEXP_CONTAINS(LOWER(source), 'lsa') 
      OR REGEXP_CONTAINS(LOWER(source), 'paid')
      OR REGEXP_CONTAINS(LOWER(source), 'ppc')
    THEN 'PPC'
    
    WHEN REGEXP_CONTAINS(LOWER(source), 'facebook') THEN 'Facebook'
    
    WHEN 
      REGEXP_CONTAINS(LOWER(source), 'gls') 
      OR REGEXP_CONTAINS(source, 'LSA') 
    THEN 'LSA'
    
    WHEN 
      (REGEXP_CONTAINS(TRIM(LOWER(source)), 'google my business')
      OR REGEXP_CONTAINS(TRIM(LOWER(source)), 'google business profile')
      OR REGEXP_CONTAINS(TRIM(LOWER(source)), 'online presence')
      OR REGEXP_CONTAINS(TRIM(source), 'GMB'))
    THEN 'GMB'

    WHEN 
      REGEXP_CONTAINS(TRIM(LOWER(source)), 'direct')
    THEN 'Direct'

    WHEN 
      REGEXP_CONTAINS(TRIM(LOWER(source)), 'bing ads')
    THEN 'Bing Ads'
  
  ELSE 'SEO'
END source_attribution,

FROM call_sources