config {
  type: "table",
  tags: ["hourly"]
}

WITH trackers AS (
  SELECT
    id,
    name AS tracker_name,
    type,
    status,
    created_at,
    disabled_at,
    sms_supported,
    whisper_message,
    JSON_EXTRACT_SCALAR(company, '$.id') AS company_id,
    destination_number,
    JSON_EXTRACT_SCALAR(number) AS tracking_phone_number
    
  FROM callrail.Trackers,
  UNNEST(JSON_EXTRACT_ARRAY(tracking_numbers)) AS number
),

water_heaters_only AS (
  SELECT
    location AS water_only_tracker_location,
    type AS water_only_traker_type,
    CONCAT('+', tracking_number) AS tracking_phone_number
  FROM google_sheets.water_heaters_only_locations
)

SELECT *
FROM trackers t
LEFT JOIN water_heaters_only w USING (tracking_phone_number)

