config {
  type: "table",
  tags: ["hourly"]
}

SELECT 
  m.client_name,
  m.clientkey,
  -- m.Industry,
  m.account_manager,
  m.client_id,
  m.callrail_id,
  m.ghl_id,
  m.lid,
  c.id,

  c.medium,
  c.source,
  c.answered,
  c.campaign,
  c.duration,
  c.keywords,
  c.call_type,
  c.formatted_call_type,
  c.direction,
  c.recording_player,
  c.company_id,
  c.call_summary,
  DATETIME(CAST(c.created_at AS TIMESTAMP), m.time_zone) created_at,
  c.first_call,
  c.utm_medium,
  c.utm_source,
  c.utm_campaign,
  c.device_type,
  c.lead_status,
  c.prior_calls,
  c.source_name,
  c.total_calls,
  c.customer_city,
  c.customer_state,
  c.customer_name,
  c.customer_country,
  c.customer_phone_number,
  c.formatted_customer_location,
  c.formatted_tracking_phone_number,
  c.formatted_tracking_source,
  c.tracking_phone_number,

  CONCAT("https://app.callrail.com/analytics/a/420424648/events/",c.person_id,"?event_id=",c.id,"&event_type=call") AS call_link,
  JSON_EXTRACT_SCALAR(speaker_percent, "$.agent") AS agent_percent,
  JSON_EXTRACT_SCALAR(speaker_percent, "$.customer") AS customer_percent,
  keywords_spotted,
  -- tag_names,
  '00000' AS sid,
--   REGEXP_EXTRACT(p.script_url, r"/companies/(\d+)/") AS sid,
  
  s.source_attribution,
  s.source_platform,

  CASE 
    WHEN s.source_attribution IN ('PPC', 'LSA') THEN 'PPC'
    ELSE s.source_attribution
  END AS source_type,
  
  IF(
        REGEXP_CONTAINS(LOWER(tag_names), 'qualified lead')
        AND NOT REGEXP_CONTAINS(LOWER(tag_names), 'unqualified')
    , 'Verified', 'Not Verified') is_verified_lead,

  CASE WHEN REGEXP_CONTAINS(LOWER(tag_names), 'booked') AND NOT REGEXP_CONTAINS(LOWER(tag_names), 'not') THEN 'Booked'
    ELSE 'Not Booked'
  END AS is_booked,

  t.tracker_name,
  t.water_only_tracker_location,
  t.water_only_traker_type

FROM callrail.Calls c
LEFT JOIN ${ref("callrail_call_tags")} USING (id, company_id)
LEFT JOIN ${ref("master_sheet")} m ON c.company_id = m.callrail_id
-- JOIN callrail.Companies p ON c.company_id = p.id
LEFT JOIN ${ref('callrail_trackers')} t USING (company_id, tracking_phone_number)
LEFT JOIN ${ref("callrail_source_attribution")} s ON s.tracker_name = t.tracker_name



