config {
  type: "table"
}

WITH raw_opps AS (
  SELECT
    id,
    name,
    source,
    status,
    contact,
    createdAt,
    updatedAt,
    locationId,
    pipelineId,
    monetaryValue,
    pipelineStageId,
    pipelineStageUId,
    lastStatusChangeAt,
    lastStageChangeAt,
    JSON_EXTRACT_SCALAR(contact, '$.email') AS contact_email,
    JSON_EXTRACT_SCALAR(contact, '$.id') AS contact_id,
    JSON_EXTRACT_SCALAR(contact, '$.name') AS contact_name,
    JSON_EXTRACT_SCALAR(contact, '$.phone') AS contact_phone,
    ARRAY_TO_STRING(
    ARRAY(
      SELECT JSON_EXTRACT_SCALAR(value, '$') 
      FROM UNNEST(JSON_EXTRACT_ARRAY(contact, '$.tags')) value
    ), 
    ','
    ) AS contact_tags,
    _airbyte_extracted_at,
    ROW_NUMBER() OVER(PARTITION BY id ORDER BY _airbyte_extracted_at DESC) rn
  FROM ghl_data.Opportunities
)

SELECT 
  r.id,
  r.name,
  r.source,
  r.status,
  r.pipelineId,
  r.monetaryValue,
  r.pipelineStageId,
  r.contact_tags,
  r.contact_id,
  r.contact_email,
  r.contact_name,
  r.contact_phone,
  r.locationId,

  DATETIME(TIMESTAMP(r.createdAt), l.timezone) AS createdAt,
  DATETIME(TIMESTAMP(r.updatedAt), l.timezone) AS updatedAt,
  DATETIME(TIMESTAMP(r.lastStageChangeAt), l.timezone) AS lastStageChangeAt,
  DATETIME(TIMESTAMP(r.lastStatusChangeAt), l.timezone) AS lastStatusChangeAt,

FROM raw_opps r 
JOIN ${ref("ghl_locations")} l ON r.locationId = l.id
WHERE rn = 1