config {
  type: "table",
  tags: ["daily"]
}

WITH raw_data AS (
  SELECT
    id AS submission_id,
    name AS contact_name,
    email AS contact_email,
    formid,
    others AS form_data,
    contactId,
    createdAt,
    -- ROW_NUMBER() OVER (PARTITION BY id ORDER BY _airbyte_extracted_at DESC) rn
  FROM ghl_extract.Form_Submissions
)

SELECT
  d,
  DATETIME(TIMESTAMP(d.createdAt), f.timezone) AS submitted_at,
  f.name AS form_name,
  f.locationId,
  f.location_name,
  JSON_VALUE(form_data, '$.eventData.source') AS source,

  CASE
    WHEN JSON_VALUE(form_data, '$.eventData.source') IN ('Paid Search', 'Paid Social', 'Social media') THEN 'PPC'
    WHEN JSON_VALUE(form_data, '$.eventData.source') = 'Organic Search' THEN 'SEO'
    ELSE 'LSA'
  END AS form_source_category,

  m.client_id,
  m.client_name,
  m.account_manager,
  m.callrail_id,
  m.clientkey,
  m.lid

FROM raw_data d
LEFT JOIN ${ref('ghl_forms')} f ON d.formid = f.id
LEFT JOIN ${ref('master_sheet')} m ON f.locationId = m.ghl_id
-- WHERE rn = 1

-- AND submission_id = '680948d121b7a629fd7fab3b'