config {
  type: "table"
}

WITH raw_appointments AS (
  SELECT
    id,
    contactId,
    title,
    dateAdded,
    startTime,
    endTime,
    calendarId,
    locationId,
    dateUpdated,
    appointmentStatus,
    _airbyte_extracted_at,
    ROW_NUMBER() OVER(PARTITION BY id ORDER BY _airbyte_extracted_at DESC) rn
  FROM ghl_data.Calendar_Events
)
SELECT 
  a.* EXCEPT(rn),

  c.name AS calender_name,

  m.client_id,
  m.client_name,
  m.clientkey,
  m.lid

FROM raw_appointments a
JOIN ${ref("master_sheet")} m ON a.locationId = m.ghl_id
JOIN ${ref("ghl_calendars")} c ON a.calendarId = c.id
WHERE rn = 1