config {
  type: "table",
  tags: ["daily"]
}

WITH ga4_properties AS (
  SELECT 
    RIGHT(name, 9) AS property,
    property_type,
    REGEXP_EXTRACT(parent, r'accounts/(\d+)') AS parent_id,
    display_name,
    industry_category,
    time_zone,
    REGEXP_EXTRACT(account, r'accounts/(\d+)') AS account_id,
  FROM google_analytics_4.properties
),

clients AS (
  SELECT DISTINCT
    clientkey,
    client_name,
    display_name,
    TRIM(gsc_name) AS gsc_url
  FROM ${ref('master_sheet')} m
  LEFT JOIN ga4_properties p ON CAST(ga4_id AS STRING) = p.property
  WHERE gsc_name IS NOT NULL
),

gsc_data AS (
  SELECT
    date,
    REPLACE(site_url, 'sc-domain:', '') AS gsc_url,
    query,
    search_type,
    impressions,
    clicks,
    position

  FROM gsc.search_analytics_by_query
)

SELECT *
FROM gsc_data
JOIN clients USING (gsc_url)
