config {
  type: "table",
  tags: ["hourly"]
}


SELECT
  client_id,
  client_name,

  -- call audit looke url
  call_auditlink,

  -- https://lookerstudio.google.com/reporting/4a46e996-b05c-4a8c-b05f-f3465a6f3c9b

  CONCAT(
    "https://lookerstudio.google.com/reporting/4a46e996-b05c-4a8c-b05f-f3465a6f3c9b?params=%7B",
    "%22ds1%22%3A%22", clientkey, "%22%2C",
    "%22ds2%22%3A%22", clientkey, "%22%2C",
    "%22ds3%22%3A%22", clientkey, "%22%2C",
    "%22ds4%22%3A%22", clientkey, "%22%2C",
    "%22ds5%22%3A%22", clientkey, "%22%2C",
    "%22ds6%22%3A%22", clientkey, "%22%2C",
    "%22ds7%22%3A%22", clientkey, "%22%2C",
    "%22ds8%22%3A%22", clientkey, "%22%2C",
    "%22ds9%22%3A%22", clientkey, "%22%2C",
    "%22ds10%22%3A%22", clientkey, "%22%7D"
  ) AS client_dashboard_url

FROM ${ref('master_sheet')}