config {
  type: "table",
  tags: ["hourly"]
}

WITH clients AS (
  SELECT
    client_id,
    clientkey,
    lid,
    client_name,
    client_logo,
    start_date,
    ghl_id,
    callrail_id,
    account_manager,
    pct_ad_spend,
    ad_spend_threshold,
    daily_management_fee,
    monthly_management_fee,
    seo_management,
    ppc_management,
    est_lead_to_service_call_ratio,
    est_average_per_booked_call_transaction_value,
    pseo_leads,
    csr_conversion_rate,
    technician_conversion_rate,
    template_name
  FROM ${ref('master_sheet')} m
),

google_ad_spend AS (
  SELECT
    clientkey,
    lid,
    date,
    SUM(CASE WHEN spend_type = 'LSA Spend' THEN ad_spend END) AS ad_spend_lsa,
    SUM(CASE WHEN spend_type = 'Google Ads Spend' THEN ad_spend END) AS ad_spend_google,
    SUM(ad_spend) google_spend
  FROM ${ref('google_ad_spend')}
  GROUP BY 1,2,3
),

meta_ad_spend AS (
  SELECT
    clientkey,
    lid,
    date,
    SUM(spend) meta_spend
  FROM ${ref('meta_ad_spend')}
  GROUP BY 1,2,3
),

bing_ad_spend AS (
  SELECT
    clientkey,
    lid,
    date,
    SUM(spend) bing_spend
  FROM ${ref('bing_ads')}
  GROUP BY 1,2,3
),

daily_calls AS (
  SELECT
    clientkey,
    lid,
    DATE(created_at) AS date,

    COUNT(CASE WHEN source_attribution = 'PPC' THEN id END) AS calls_ppc,
    COUNT(CASE WHEN source_attribution = 'GBP' THEN id END) AS calls_gmb,
    COUNT(CASE WHEN source_attribution = 'SEO' THEN id END) AS calls_seo,
    COUNT(CASE WHEN source_attribution = 'LSA' THEN id END) AS calls_lsa,
    COUNT(id) AS calls_total,
    COUNT(CASE WHEN formatted_call_type = 'Answered Call' THEN id END) AS calls_answered

  FROM ${ref('callrail_calls')}
  GROUP BY 1,2,3
),


daily_forms AS (
  SELECT
    clientkey,
    lid,
    DATE(submitted_at) AS date,
    COUNT(CASE WHEN form_source_category = 'PPC' THEN submission_id END) AS forms_ppc,
    COUNT(CASE WHEN form_source_category = 'LSA' THEN submission_id END) AS forms_lsa,
    COUNT(CASE WHEN form_source_category = 'SEO' THEN submission_id END) AS forms_seo,
    COUNT(1) AS daily_forms
  FROM ${ref('ghl_form_submissions')}
  GROUP BY 1,2,3
),

lsa_responsiveness AS (
  SELECT
    clientkey,
    lid,
    date,
    SUM(total_leads) AS total_lsa_leads,
    SUM(responded_leads) AS total_lsa_responded_leads,
    AVG(avg_response_time_minutes) AS avg_response_time_minutes
  FROM ${ref('google_local_service_leads_responsiveness')}
  GROUP BY 1,2,3
)

SELECT
  d.client_id,
  d.client_name,
  d.clientkey,
  d.lid,
  d.date,
  d.month,
  
  m.client_logo,
  m.start_date,
  m.ghl_id,
  m.callrail_id,
  m.ad_spend_threshold,
  m.pct_ad_spend,
  m.daily_management_fee,
  m.monthly_management_fee,
  m.seo_management,
  m.ppc_management,
  m.est_lead_to_service_call_ratio,
  m.est_average_per_booked_call_transaction_value,
  m.pseo_leads,
  m.csr_conversion_rate,
  m.technician_conversion_rate,
  m.template_name,
  m.account_manager,



  g.ad_spend_lsa,
  g.ad_spend_google,
  g.google_spend,

  ms.meta_spend,
  bs.bing_spend,

  IFNULL(g.google_spend, 0) + IFNULL(ms.meta_spend, 0) + IFNULL(bs.bing_spend, 0) AS ad_spend_total,

  c.calls_ppc,
  c.calls_gmb,
  c.calls_seo,
  c.calls_lsa,
  c.calls_total,

  f.forms_ppc,
  f.forms_lsa,
  f.forms_seo,
  f.daily_forms,

  gas.add_service_fee,

  IFNULL(c.calls_total,0) + IFNULL(f.daily_forms,0) AS total_leads,

  (IFNULL(c.calls_total,0) + IFNULL(f.daily_forms,0)) * IFNULL(m.pseo_leads, 0.85) AS qualified_leads,
  
  ((IFNULL(m.monthly_management_fee,0) + IFNULL(m.seo_management,0) + IFNULL(m.ppc_management,0)) * 12) / 365 AS daily_service_fee,

  (IFNULL(c.calls_total,0) + IFNULL(f.daily_forms,0)) * IFNULL(m.pseo_leads,1) * IFNULL(m.csr_conversion_rate, 0.85) AS csr_conversions,

  ((IFNULL(c.calls_total,0) + IFNULL(f.daily_forms,0)) * IFNULL(m.pseo_leads,1) * IFNULL(m.csr_conversion_rate, 1)) * IFNULL(m.technician_conversion_rate, 0.75) AS technical_conversions,

  (((IFNULL(c.calls_total,0) + IFNULL(f.daily_forms,0)) * IFNULL(m.pseo_leads,1) * IFNULL(m.csr_conversion_rate, 1)) * IFNULL(m.technician_conversion_rate, 0.75)) * IFNULL(CAST(est_average_per_booked_call_transaction_value AS FLOAT64),450) AS projected_revenue,

  lsar.total_lsa_leads AS lsar_total_lsa_leads,
  lsar.total_lsa_responded_leads AS lsar_total_lsa_responded_leads,
  lsar.avg_response_time_minutes AS lsar_avg_response_time_minutes



FROM ${ref('_dates')} d
LEFT JOIN clients m USING (clientkey, lid)
LEFT JOIN google_ad_spend g USING (clientkey, lid, date)
LEFT JOIN daily_calls c USING (clientkey, lid, date)
LEFT JOIN daily_forms f USING (clientkey, lid, date)
LEFT JOIN meta_ad_spend ms USING (clientkey, lid, date)
LEFT JOIN bing_ad_spend bs USING (clientkey, lid, date)
LEFT JOIN lsa_responsiveness lsar USING (clientkey, lid, date)
LEFT JOIN ${ref('google_additional_service_fee')} gas USING (clientkey, lid, date)



