config {
  type: "table",
  tags: ["hourly"]
}


WITH clients AS (
  SELECT
    client_id,
    clientkey,
    lid,
    client_name,
    ghl_id,
    callrail_id,
    IFNULL(monthly_management_fee,0) monthly_management_fee,
    -- IFNULL(seo_management,0) seo_management,
    -- IFNULL(ppc_management,0) ppc_management
  FROM ${ref('master_sheet')}
),

months AS (
  SELECT
    clientkey,
    lid,
    month
  FROM ${ref('_dates')}
  JOIN clients USING (clientkey, lid)
)

SELECT 
  client_id,
  clientkey,
  lid,
  client_name,
  ghl_id,
  callrail_id,
  monthly_management_fee,
  -- seo_management,
  -- ppc_management,
  -- monthly_management_fee + seo_management + ppc_management AS monthly_fee,
  monthly_management_fee AS monthly_fee,
  month
FROM months
JOIN clients USING (clientkey, lid)
