config {
  type: "table",
  disabled: true
}

WITH clients AS (
  SELECT
    clientkey,
    lid,
    ghl_id,
    callrail_id,
    IFNULL(daily_management_fee,0) daily_management_fee,
  FROM ${ref('master_sheet')}
)

SELECT 
  client_id,
  clientkey,
  lid,
  client_name,
  ghl_id,
  callrail_id,
  daily_management_fee,
  date,
  month,
FROM ${ref('_dates')}
JOIN clients USING (clientkey, lid)
WHERE daily_management_fee != 0