
config {
  type: "table"
}

SELECT 
  client_id,
  SUBSTR(TO_BASE64(SHA256(CAST(TRIM(client_name) AS STRING))), 1, 8) AS clientkey,
  TRIM(client_name) client_name,
  PARSE_DATE('%Y/%m/%d', start_date) AS start_date,
  location_id AS lid,
  client_logo,
  ghl_id,
  ghl_name,
  ga_4_id AS ga4_id,
  ga_4_name AS ga4_name,
  callrail_id,
  callrail_name,
  
  SAFE_CAST(google_ad_id AS INT64) AS google_ad_id,
  google_ad_name,
  SAFE_CAST(google_ad_id_2 AS INT64) AS google_ad_id_2,
  SAFE_CAST(google_ad_id_3 AS INT64) AS google_ad_id_3,
  SAFE_CAST(google_ad_id_4 AS INT64) AS google_ad_id_4,
  SAFE_CAST(google_ad_id_5 AS INT64) AS google_ad_id_5,
  SAFE_CAST(google_ad_id_6 AS INT64) AS google_ad_id_6,
  SAFE_CAST(google_ad_id_7 AS INT64) AS google_ad_id_7,
  SAFE_CAST(google_ad_id_8 AS INT64) AS google_ad_id_8,
  SAFE_CAST(google_ad_id_9 AS INT64) AS google_ad_id_9,
  SAFE_CAST(google_ad_id_10 AS INT64) AS google_ad_id_10,

  gsc_property_id,

--   pct_ad_spend,
  ad_spend_threshold,

  gsc_name,
  gmb_location_id,
  gmb_name,
  account_manager,
  status,
  pct_ad_spend_charge,
  daily_management_fee,
  monthly_management_fee,
  seo_management,
  ppc_management,
  est_lead_to_service_call_ratio,
  es_average_per_booked_call_transaction_value AS est_average_per_booked_call_transaction_value,
  pseo_leads_ pseo_leads,
  csr_conversion_rate,
  technician_conversion_rate,
  template_name

FROM plumberseo.google_sheets.master_sheet