config {
  type: "table",
  tags: ["hourly"]
}

SELECT 
  client_id,
  SUBSTR(REGEXP_REPLACE(TO_BASE64(SHA256(CAST(client_name AS STRING))),r'[^A-Za-z0-9]', ''),1, 8) AS clientkey,
  -- SUBSTR(TO_BASE64(SHA256(CAST(TRIM(client_name) AS STRING))), 1, 8) AS clientkey,
  TRIM(client_name) AS client_name,
  PARSE_DATE('%Y/%m/%d', start_date) AS start_date,
  location_id AS lid,
  client_logo,
  ghl_id,
  ghl_name,
  ghl_pit,
  ga_4_id AS ga4_id,
  ga_4_name AS ga4_name,
  callrail_id,
  callrail_name,
  
  google_ad_id AS google_ad_id,
  google_ad_name,
  SAFE_CAST(REPLACE(google_ad_id_2, '-', '') AS INT64) AS google_ad_id_2,
  SAFE_CAST(REPLACE(google_ad_id_3, '-', '') AS INT64) AS google_ad_id_3,
  SAFE_CAST(REPLACE(google_ad_id_4, '-', '') AS INT64) AS google_ad_id_4,
  SAFE_CAST(REPLACE(google_ad_id_5, '-', '') AS INT64) AS google_ad_id_5,
  SAFE_CAST(REPLACE(google_ad_id_6, '-', '') AS INT64) AS google_ad_id_6,
  SAFE_CAST(REPLACE(google_ad_id_7, '-', '') AS INT64) AS google_ad_id_7,
  SAFE_CAST(REPLACE(google_ad_id_8, '-', '') AS INT64) AS google_ad_id_8,
  SAFE_CAST(REPLACE(google_ad_id_9, '-', '') AS INT64) AS google_ad_id_9,
  SAFE_CAST(REPLACE(google_ad_id_10, '-', '') AS INT64) AS google_ad_id_10,

  gsc_property_id,

  facebook_ad_id,
  bing_ad_id,
  TRIM(call_auditlink) AS call_auditlink,

  pct_ad_spend, 
  ad_spend_threshold,

  gsc_name,
  CAST(gmb_location_id AS STRING) gmb_location_id,
  CAST(gmb_location_id_2 AS STRING) gmb_location_id_2,
  CAST(gmb_location_id_3 AS STRING) gmb_location_id_3,
  CAST(gmb_location_id_4 AS STRING) gmb_location_id_4,

  account_manager,
  status,
  pct_ad_spend_charge,
  -- SAFE_CAST(daily_management_fee AS FLOAT64) daily_management_fee,
  SAFE_CAST(monthly_management_fee AS FLOAT64) monthly_management_fee,
  SAFE_CAST(lsa_management_fee AS FLOAT64) lsa_management_fee,
  -- SAFE_CAST(seo_management AS FLOAT64) seo_management,
  -- SAFE_CAST(ppc_management AS FLOAT64) ppc_management,
  est_lead_to_service_call_ratio,
  es_average_per_booked_call_transaction_value AS est_average_per_booked_call_transaction_value,
  pseo_leads_ AS pseo_leads,
  csr_conversion_rate,
  technician_conversion_rate,
  template_name,
  "America/New_York" AS time_zone,

FROM plumberseo.google_sheets.master_sheet
WHERE status = 'Active'
