
config {
  type: "table"
}

SELECT 
  client_id,
  client_name,
  PARSE_DATE('%Y/%m/%d', start_date) AS start_date,
  ghl_id,
  ghl_name,
  ga_4_id AS ga4_id,
  ga_4_name AS ga4_name,
  callrail_id,
  callrail_name,
  google_ad_id,
  google_ad_name,
  gsc_property_id,
  gsc_name,
  gmb_location_id,
  gmb_name,
  account_manager,
  status,
  daily_management_fee,
  monthly_management_fee,
  seo_management,
  ppc_management,
  est_lead_to_service_call_ratio,
  es_average_per_booked_call_transaction_value AS est_average_per_booked_call_transaction_value,
  pseo_leads_ pseo_leads,
  csr_conversion_rate,
  technician_conversion_rate,
  template_name
FROM plumberseo.google_sheets.master_sheet