config {
  type: "table",
  tags: ["hourly"]
}

WITH client_locations AS (
  SELECT 
    clientkey,
    client_name,
    lid,
    gmb_location_id
  FROM ${ref("master_sheet")}
  WHERE gmb_location_id IS NOT NULL

  UNION ALL

  SELECT 
    clientkey,
    client_name,
    lid,
    gmb_location_id_2
  FROM ${ref("master_sheet")}
  WHERE gmb_location_id_2 IS NOT NULL

  UNION ALL

  SELECT 
    clientkey,
    client_name,
    lid,
    gmb_location_id_3
  FROM ${ref("master_sheet")}
  WHERE gmb_location_id_3 IS NOT NULL

  UNION ALL

  SELECT 
    clientkey,
    client_name,
    lid,
    gmb_location_id_4
  FROM ${ref("master_sheet")}
  WHERE gmb_location_id_4 IS NOT NULL
),

gmb_locations AS (
  SELECT 
    id AS gmb_location_id, 
    title, 
    storefront_address_locality, 
    metadata_maps_uri
  FROM google_business_profile.location
  
)

SELECT *
FROM client_locations
JOIN gmb_locations USING (gmb_location_id)
