config {
  type: "table"
}


WITH clients AS (
  SELECT
    client_id,
    client_name,
    ghl_id,
    callrail_id,
    IFNULL(monthly_management_fee,0) monthly_management_fee,
    IFNULL(seo_management,0) seo_management,
    IFNULL(ppc_management,0) ppc_management
  FROM ${ref('master_sheet')}
),

months AS (
  SELECT
    client_id,
    client_name,
    _month
  FROM ${ref('_dates')}
  JOIN clients USING (client_id, client_name)
  GROUP BY 1,2,3
)

SELECT 
  client_id,
  client_name,
  ghl_id,
  callrail_id,
  monthly_management_fee,
  seo_management,
  ppc_management,
  monthly_management_fee + seo_management + ppc_management AS monthly_fee,
  _month
FROM months
JOIN clients USING (client_id, client_name)