config {
  type: "table",
  tags: ["hourly"]
}

WITH accounts AS (
  SELECT id AS customer_id, descriptive_name, time_zone
  FROM google_ads.account_history
  WHERE _fivetran_active IS TRUE

  UNION ALL

  SELECT id AS customer_id, descriptive_name, time_zone
  FROM lsa_mcc.account_history
  WHERE _fivetran_active IS TRUE
  AND id NOT IN (SELECT DISTINCT id FROM google_ads.account_history)
),

google_ad_ids AS (
  SELECT 
    client_id,
    lid,
    clientkey,
    client_name,
    google_ad_id AS customer_id
  FROM ${ref('master_sheet')}
  WHERE google_ad_id IS NOT NULL

  UNION ALL

  SELECT 
    client_id,
    lid,
    clientkey,
    client_name,
    google_ad_id_2 AS customer_id
  FROM ${ref('master_sheet')}
  WHERE google_ad_id_2 IS NOT NULL

  UNION ALL

  SELECT 
    client_id,
    lid,
    clientkey,
    client_name,
    google_ad_id_3 AS customer_id
  FROM ${ref('master_sheet')}
  WHERE google_ad_id_3 IS NOT NULL

  UNION ALL

  SELECT 
    client_id,
    lid,
    clientkey,
    client_name,
    google_ad_id_4 AS customer_id
  FROM ${ref('master_sheet')}
  WHERE google_ad_id_4 IS NOT NULL

    UNION ALL

  SELECT 
    client_id,
    lid,
    clientkey,
    client_name,
    google_ad_id_5 AS customer_id
  FROM ${ref('master_sheet')}
  WHERE google_ad_id_5 IS NOT NULL

    UNION ALL

  SELECT 
    client_id,
    lid,
    clientkey,
    client_name,
    google_ad_id_6 AS customer_id
  FROM ${ref('master_sheet')}
  WHERE google_ad_id_6 IS NOT NULL

    UNION ALL

  SELECT 
    client_id,
    lid,
    clientkey,
    client_name,
    google_ad_id_7 AS customer_id
  FROM ${ref('master_sheet')}
  WHERE google_ad_id_7 IS NOT NULL

    UNION ALL

  SELECT 
    client_id,
    lid,
    clientkey,
    client_name,
    google_ad_id_8 AS customer_id
  FROM ${ref('master_sheet')}
  WHERE google_ad_id_8 IS NOT NULL

    UNION ALL

  SELECT 
    client_id,
    lid,
    clientkey,
    client_name,
    google_ad_id_9 AS customer_id
  FROM ${ref('master_sheet')}
  WHERE google_ad_id_9 IS NOT NULL

    UNION ALL

  SELECT 
    client_id,
    lid,
    clientkey,
    client_name,
    google_ad_id_10 AS customer_id
  FROM ${ref('master_sheet')}
  WHERE google_ad_id_10 IS NOT NULL
)

SELECT DISTINCT *
FROM google_ad_ids
JOIN accounts USING (customer_id)