config {
  type: "table"
}


WITH local_service_leads AS (
  SELECT
    customer_id,
    creation_date_time,
    id AS lead_id,
    credit_details_credit_state,
    lead_charged,
    lead_status,
    lead_type,
    CASE
      WHEN lead_charged = TRUE AND (credit_details_credit_state IS NULL OR credit_details_credit_state = 'UNSPECIFIED') THEN 'charged'
      WHEN lead_charged = TRUE AND credit_details_credit_state = 'CREDITED' THEN 'credited'
      WHEN lead_charged = TRUE AND credit_details_credit_state = 'PENDING' THEN 'pending'
      WHEN lead_charged = FALSE THEN 'not charged'
      ELSE 'unknown'
    END AS charge_status
  FROM google_ads.local_services_lead

  UNION ALL

  SELECT
    customer_id,
    creation_date_time,
    id AS lead_id,
    credit_details_credit_state,
    lead_charged,
    lead_status,
    lead_type,
    CASE
      WHEN lead_charged = TRUE AND (credit_details_credit_state IS NULL OR credit_details_credit_state = 'UNSPECIFIED') THEN 'charged'
      WHEN lead_charged = TRUE AND credit_details_credit_state = 'CREDITED' THEN 'credited'
      WHEN lead_charged = TRUE AND credit_details_credit_state = 'PENDING' THEN 'pending'
      WHEN lead_charged = FALSE THEN 'not charged'
      ELSE 'unknown'
    END AS charge_status
  FROM lsa_mcc.local_services_lead
)

SELECT
  * EXCEPT(creation_date_time),
  DATETIME(TIMESTAMP(creation_date_time, 'UTC'), c.time_zone ) AS created_at,

FROM local_service_leads l
JOIN ${ref('google_ad_ids')} c USING (customer_id)
