config {
  type: "table"
}

WITH google_campaigns AS (
  SELECT 
      id AS campaign_id,
      customer_id,
      advertising_channel_type, 
      name AS campaign_name
  FROM google_ads.campaign_history
  WHERE _fivetran_active IS TRUE

  UNION ALL

  SELECT 
    id AS campaign_id,
    customer_id,
    advertising_channel_type, 
    name AS campaign_name
  FROM lsa_mcc.campaign_history
  WHERE _fivetran_active IS TRUE
),

compaign_stats AS (
  SELECT
    date,
    customer_id,
    id AS campaign_id,
    SUM(SAFE_DIVIDE(cost_micros, 1000000)) AS ad_spend,
    SUM(clicks) AS clicks,
    SUM(impressions) AS impressions,
    SUM(conversions) AS conversions
  FROM google_ads.campaign_stats
  GROUP BY date, customer_id, id

  UNION ALL

  SELECT
    date,
    customer_id,
    id AS campaign_id,
    SUM(SAFE_DIVIDE(cost_micros, 1000000)) AS ad_spend,
    SUM(clicks) AS clicks,
    SUM(impressions) AS impressions,
    SUM(conversions) AS conversions
  FROM lsa_mcc.campaign_stats
  GROUP BY date, customer_id, id
),

google_ads_spend AS (
  SELECT *
  FROM compaign_stats cs 
  JOIN google_campaigns gc USING(customer_id, campaign_id)
)

SELECT 
   *,
   CASE 
    WHEN advertising_channel_type = 'LOCAL_SERVICES' THEN 'LSA Spend'
    ELSE 'Google Ads Spend'
   END AS spend_type
FROM google_ads_spend AS gads
LEFT JOIN ${ref("google_ad_ids")} c USING(customer_id)
LEFT JOIN ${ref('google_ads_impressions')} i USING (campaign_id, date)

