config {
  type: "table"
}

SELECT 
  client_id,
  lid,
  clientkey,
  client_name,
  google_ad_id AS customer_id
FROM ${ref('master_sheet')}
WHERE google_ad_id IS NOT NULL

UNION ALL

SELECT 
  client_id,
  lid,
  clientkey,
  client_name,
  google_ad_id_2 AS customer_id
FROM ${ref('master_sheet')}
WHERE google_ad_id_2 IS NOT NULL

UNION ALL

SELECT 
  client_id,
  lid,
  clientkey,
  client_name,
  google_ad_id_3 AS customer_id
FROM ${ref('master_sheet')}
WHERE google_ad_id_3 IS NOT NULL

UNION ALL

SELECT 
  client_id,
  lid,
  clientkey,
  client_name,
  google_ad_id_4 AS customer_id
FROM ${ref('master_sheet')}
WHERE google_ad_id_4 IS NOT NULL