config {
  type: "table"
}

SELECT 
  client_id,
  lid,
  clientkey,
  client_name,
  google_ad_id
FROM ${ref('master_sheet')}
WHERE google_ad_id IS NOT NULL

UNION ALL

SELECT 
  client_id,
  lid,
  clientkey,
  client_name,
  google_ad_id_2 AS google_ad_id
FROM ${ref('master_sheet')}
WHERE google_ad_id_2 IS NOT NULL

UNION ALL

SELECT 
  client_id,
  lid,
  clientkey,
  client_name,
  google_ad_id_3 AS google_ad_id
FROM ${ref('master_sheet')}
WHERE google_ad_id_3 IS NOT NULL

UNION ALL

SELECT 
  client_id,
  lid,
  clientkey,
  client_name,
  google_ad_id_4 AS google_ad_id
FROM ${ref('master_sheet')}
WHERE google_ad_id_4 IS NOT NULL